version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
      - "ci"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "cargo"
    directory: "/workers/rust"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "rust"
    labels:
      - "dependencies"
      - "rust"

  - package-ecosystem: "cargo"
    directory: "/adapters/spdk_rust"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "rust"
    labels:
      - "dependencies"
      - "rust"

  - package-ecosystem: "cargo"
    directory: "/adapters/silent_payments_rust"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "rust"
    labels:
      - "dependencies"
      - "rust"

  - package-ecosystem: "cargo"
    directory: "/adapters/bip352_rust"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "rust"
    labels:
      - "dependencies"
      - "rust"

  - package-ecosystem: "cargo"
    directory: "/adapters/bdk_sp_rust"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "rust"
    labels:
      - "dependencies"
      - "rust"

  - package-ecosystem: "gomod"
    directory: "/adapters/go_bip352"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "go"
    labels:
      - "dependencies"
      - "go"
