[package]
name = "sp-differ-semantic-adapter-silent-payments"
version = "0.1.0"
edition = "2021"

[lib]
name = "sp_differ_semantic_worker_silent_payments"
crate-type = ["cdylib", "rlib"]

[dependencies]
bdk_sp = { package = "silent-payments-bdk-sp", version = "0.1.1" }
bitcoin = "0.32"
hex = "0.4"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
silent-payments = "0.1.1"
